### ISSUE TITLE
Make it possible to adjust alerts

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/com.ruuvi.station.webui#10]
Make user experience same or almost same with the mobile apps. Additionally a number field could be used, not just sliders.

**Comment by io53** [comment]
Hm. yeah true. But how it this suppose to work.. Should the persons email not show in the list before he has accepted the share?
It seems like the API does not return the user that you shared to before he has accepted the share(?). But it would make the UI sharing a bit confusing if we didn't show any result of the share 🤔.

If trying to unshare to a user who has no account the backend returns:
404
{
    "result": "error",
    "error": "User not found.",
    "code": "ER_USER_NOT_FOUND"
}

So that it mean you cannot unshare if the user does not have an account?
