### ISSUE TITLE
UI fix - Success/Error/Info colors

### ISSUE THREAD

**Issue by sini-maaria** [ruuvi/com.ruuvi.station.webui#143]
![Screenshot 2022-02-24 at 10 35 29](https://user-images.githubusercontent.com/19531763/155488392-45e9fb58-e6f4-4e6b-817e-2795bb4f7a63.png)

![Screenshot 2022-02-24 at 10 35 38](https://user-images.githubusercontent.com/19531763/155488400-f29ce409-176f-48bf-967f-4dc201542192.png)

**Comment by sini-maaria** [comment]
Notice the possibility to use Regular font in info box.

**Comment by io53** [comment]
Todo:
Change info background color to the same as page background color
Make toast paragraph space smaller

**Comment by laurijamsa** [comment]
I'm not sure if the spec was to change only the colors or also remove the icons and closing button but I would suggest not to remove the closing button at least from the info popups because now for example the info popups that have longer timeout are annoying because user cannot close them. Another note is that without the icons it feels like that the texts should be centered especially on other than info popups.

Original:
![image](https://user-images.githubusercontent.com/1311912/158310790-e9c27df4-412e-4c9f-919c-ef98f95715cd.png)

![image](https://user-images.githubusercontent.com/1311912/158310704-b71fbe48-e264-41bb-8e18-5172c3f9b5e9.png)

New:
![image](https://user-images.githubusercontent.com/1311912/158310844-ccb4feab-f89f-4f54-8f4d-cc441532dc30.png)

![image](https://user-images.githubusercontent.com/1311912/158310724-7613e015-e778-4e48-bf26-dbc4dfa92616.png)

**Comment by sini-maaria** [comment]
- I would leave the both, close x and icon.

- This looks a bit tight, so please add padding (5-10px) to all the sides and at least 30px under the box.

![Screenshot 2022-03-15 at 8 18 51](https://user-images.githubusercontent.com/19531763/158319266-433e2d0f-d566-4bad-a6e2-9b36496bb12b.png)
