### ISSUE TITLE
Test the banner feature for bragging about new features

### ISSUE THREAD

**Issue by markoaamunkajo** [ruuvi/com.ruuvi.station.webui#371]
Description:

Let's test this banner on dev and add details how to update the file on this card for future reference

**Comment by io53** [comment]
Currently the banner content is fetched from (dev)station.ruuvi.com/notification.json
The content of the file can currently only be edited on server at /var/www/html/notification.json

To make it simpler the file could be moved to somewhere more convenient or even add support to fetch banner content from ruuvi cloud.

Format is 

```
[
    {
        "plan": "",
        "key": "20231115",
        "en": "Version 0.10.1 is released! Check what's changed <a href='https://f.ruuvi.com/t/5039/9999' style='text-decoration: underline;' target='_blank'>here</a>.",
        "fi": "Versio 0.10.1 on julkaistu! Tarkista muutokset <a href='https://f.ruuvi.com/t/5039/9999' style='text-decoration: underline;' target='_blank'>täältä</a>.",
        "sv": "Version 0.10.1 har släppts! Kolla vad som har ändrats <a href='https://f.ruuvi.com/t/5039/9999' style='text-decoration: underline;' target='_blank'>här</a>."
    }
]
```

There can be multiple notifications so that there can be different notifications for different plans like so:

```
[
    {
        "plan": "Free",
        "key": "key0",
        "en": "en contnet free",
        "fi": "fi content free",
        "sv": "sv content free"
    },
    {
        "plan": "Pro",
        "key": "key0",
        "en": "en contnet pro",
        "fi": "fi content pro",
        "sv": "sv content pro"
    }
]
```

"plan": ""  means to all
"plan": "Free" is shown to Free subscribers and so on..

Only the first matching banner for the user will be shown.

"key" is used to keep track of what banner has been shown, the browser will keep a list of already shown banner in storage. 
Change the key when making a new banner, else it will not show up for the users.

**Comment by markoaamunkajo** [comment]
@io53 Let's add showing two banners at once as discussed on the channel

**Comment by markoaamunkajo** [comment]
@io53 it's not working as expected for me on devstation.ruuvi.com 


I have edited the json file in GitHub (https://github.com/ruuvi/station.localization/blob/dev/web_banners.json), changes were merged and no banners are showing for me. Maybe I'm doing something wrong.

**Comment by markoaamunkajo** [comment]
Missing , in json was fixed and now banners work. This task is completed.
