### ISSUE TITLE
Chart precision doesn't adhere to settings

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#381]
User has temperature precision set to integer F (  1F )

Current temperature in box is correct

Cursor value format varies as cursor is moved
for example 38,8  39,2    .
Additionally Locale not adhered to, example 
is 38,8
SB 38.8

![image](https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/3040c88b-4024-481c-a69d-7d05ff3345b0)

**Comment by markoaamunkajo** [comment]
Let's improve this so that calculation is always done with precise values for

Last datapoint
Min/Max/Avg
Selected datapoint

But will be shown according to resolution that user has selected in settings

**Comment by laurijamsa** [comment]
Hmm, seems that we forgot to update the requirement spec on webui after we decided in the mobile meeting that the current selected datapoint values should be in 0.01 resolution even if user has selected 0.1 or 1 as resolution setting in the settings. That user setting should affect everything else including min/max/average except here in the datapoint value when user is selecting a datapoint by hovering mouse on it:

<img width="281" alt="image" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/1311912/9ac5f9b8-10dd-4387-bd6d-1b6530e4ac9d">

Otherwise this seems to work well enough. I can see that after updating the setting, graph needs to be updated so that min/max/average will refresh but it's fine.
