### ISSUE TITLE
Use browser's localisation settings for decimal pointer and date styles

### ISSUE THREAD

**Issue by DG12** [ruuvi/com.ruuvi.station.webui#398]
<img width="304" alt="web SeqNumber_missingPunct" src="https://github.com/ruuvi/com.ruuvi.station.webui/assets/2365961/70322847-8002-4fb5-87f2-370d18ee1527">

**Comment by laurijamsa** [comment]
The webUI layout does not support localisation styles depending on user's web browser's localisation settings. Meaning, currently it is hardcoded to show for example decimal pointers as commas (not periods as US users would like to see).

We can leave this issue open because we should have the localisation support on our roadmap at some point. I will modify the original issue title to reflect the task itself.

**Comment by DG12** [comment]
Actually, as shown in the screen print there is NO punctation at all. :-)

**Comment by markoaamunkajo** [comment]
![Image](https://github.com/user-attachments/assets/329683f1-de15-4d6c-a978-810c34113f39)
![Image](https://github.com/user-attachments/assets/5879f893-c917-447f-b59e-4da2f894a0ca)

**Comment by markoaamunkajo** [comment]
Discussed on channel, this is ok now
